### ISSUE TITLE
better way to create an area matrix?

### ISSUE THREAD

**Issue by yonebayashi** [Reed-CS-Club/interview-study-group#1]
https://github.com/Reed-CS-Club/interview-study-group/blob/b1ece0902d3cf5263b417fc71a716f6604873a52/problems/valid-sudoku.py#L9-L33

**Comment by daherrero** [comment]
Instead of allocating a new matrix we can get the index of each sub-box from row and col using i and j:
`(i // 3 ) * 3 + j // 3`.
